name: taxonomy_conda_environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - blast=2.12.*
  - fastqc=0.11.*
  - multiqc=1.11
  - bowtie2=2.4.*
  - cutadapt=3.5
  - samtools=1.14
  - seqtk=1.3
  # - nextflow=20.10.*
  - r-base=4.1.*
  - r-tidyverse=1.3.*
  - r-openxlsx=4.2.* 
  - r-egg=0.4.*
  - cd-hit=4.8.*
  - cd-hit-auxtools=4.8.*
  - spades=3.15.*
  - perl-dbi=1.642
  - perl-dbd-sqlite=1.64
  - perl-lwp-simple=6.15
  - diamond=2.0.*
